### ISSUE TITLE
'Denpa\Bitcoin\Providers\ServiceProvider' not found

### ISSUE THREAD

**Issue by icangku** [denpamusic/laravel-bitcoinrpc#1]
'Denpa\Bitcoin\Providers\ServiceProvider' not found i don't know what's wrong

**Comment by denpamusic** [comment]
Hi!
Sorry for not replying for so long, had almost no access to internet for half a year.
Please check that you correctly registered provider in /config/app.php file (look for Denpa\Bitcoin\Providers\ServiceProvider::class).
If it's there, run "composer dump-autoload" in project dir and see if error goes away.

**Comment by denpamusic** [comment]
Closed on no response.
