### ISSUE TITLE
FatalErrorException on newest release

### ISSUE THREAD

**Issue by cpass78** [denpamusic/laravel-bitcoinrpc#13]
Hello,

I just ran composer update on a wip app and am getting hit with this error now: `Declaration of Denpa\Bitcoin\LaravelClient::getResponseHandler() must be compatible with Denpa\Bitcoin\Client::getResponseHandler(): string`

Using 1.2.8 on Laravel Framework 5.7.15

Thanks

**Comment by denpamusic** [comment]
Hi,

Thank you for your report!
Reason for this error was incorrect dependency version in composer.json.
It should be fixed now with version 1.2.8.1.
Try running update again and see if it works.

**Comment by cpass78** [comment]
Yep perfect, thank you 👍
