### ISSUE TITLE
Entity Too Large 

### ISSUE THREAD

**Issue by jiyongieee** [denpamusic/laravel-bitcoinrpc#21]
Client error: `POST <public IP address removed>` resulted in a `413 Request Entity Too Large` response:

I got error when using decoderawtransaction. I already set the post_max_size = 2G and upload_max_filesize = 2G in php.ini. In apache, I already set the bodylimitrequest = 100MB.

Where do I need to change in order to pass this error? Thank you.

**Comment by denpamusic** [comment]
The directive for apache is called [LimitRequestBody](https://httpd.apache.org/docs/2.4/mod/core.html#LimitRequestBody), not bodylimitrequest.
Maybe this is why you're getting this error.

**Comment by jiyongieee** [comment]
Actually I already tried this line LimitRequestBody 104857600. I read about JSON RPC and it stated there limit size is 20MB. May I know the limit size for your JSON RPC?

**Comment by denpamusic** [comment]
This is just a client, it doesn't enforce any limit on request size by itself. Request limit can only be enforced by the server (in this case Bitcoin daemon) Sadly I've found no mention about any request size limits in [Bitcoin docs](https://bitcoin.org/en/developer-reference#bitcoin-core-apis) or for that matter in [JSON-RPC 2.0 specs](https://www.jsonrpc.org/specification). I'm sorry, but as this is server error, not a client one I can't help you much. Try to raise an issue in bitcoin repo about what is the maximum size of request for Core API.

**Comment by denpamusic** [comment]
Also I suggest you to use [bitwasp/bitcoin](https://packagist.org/packages/bitwasp/bitcoin) instead of sending decoderawtransaction to the daemon to bypass this error.
```php
use BitWasp\Bitcoin\Transaction\Transaction;

$transaction = Transaction::fromHex("<your raw transaction hex string>");
```

**Comment by jiyongieee** [comment]
I already raised this issue on bitcoin github. I will try using this bitwasp/bitcoin. I will update you later after trying this. Thank you.
