### ISSUE TITLE
Request response containing an object with multiple same key is merged and data is missing

### ISSUE THREAD

**Issue by bynicolas** [denpamusic/laravel-bitcoinrpc#23]
**Describe the bug**
The request results are merged when the keys are the same. This causes issues with some RPC commands that have results containing the same "key" part. For instance, a `masternode outputs` rpc command that have multiple results with the same `txid` as key and a different `index` as value.

**To Reproduce**
a `bitcoind()->client()->request('masternode','outputs')->get();` should give you the bug as long as there is multiple outputs that have the same `txid` but different output `index`.

**Expected behavior**
I would expect the results be returned unaltered or to the very least, expose a method that would return the *raw* results.

**Logs**
This is a sample of an answer to the `masternode output` command from the wallet console
```
{
  "1fff541fd048b032aca39cd4ed1a864b05cfa3b596bd02a471d807eb7cee4981": "1",
  "1fff541fd048b032aca39cd4ed1a864b05cfa3b596bd02a471d807eb7cee4981": "2",
  "1fff541fd048b032aca39cd4ed1a864b05cfa3b596bd02a471d807eb7cee4981": "3",
  "11c07462fd35e438b6587c255e765912c8482c8fdc37191b102a1a2758eb4177": "1"
}
```
in that example, `laravel-bitcoinrpc` will return

```
{
  "1fff541fd048b032aca39cd4ed1a864b05cfa3b596bd02a471d807eb7cee4981": "3",
  "11c07462fd35e438b6587c255e765912c8482c8fdc37191b102a1a2758eb4177": "1"
}
```

**Cryptocurrency**
Describe used software and network:
* Software: PACGlobal Core v0.14.0.3
* Network: mainnet and testnet

**Environment**
Describe your runtime environment:
* Laravel: 6.0.3
* PHP: 7.3.9
* Web Server (if applicable): nginx/1.17.1
* System: macOS

**Comment by denpamusic** [comment]
Hi, thank you for detailed bug report!

This is to be expected, as `json_decode()` can't deal with different values under the same key, so it'll only use latest encountered key.

I'll try to figure out a way to deal with this, but it'll probably not be a priority, since original Bitcoin Core has no endpoints like this, and it's not really recommended way to use JSON - as [RFC7159](https://tools.ietf.org/html/rfc7159#section-4) says `The names within an object SHOULD be unique.`

However, there is a way to get raw response as returned by guzzle:
`$response = bitcoind()->request('masternode', 'outputs')->response();` from there you can get body as string via `echo $response->getBody()->_toString();` You'll then need to create custom parser for this string, since `json_decode()` won't work - as described in the second paragraph.

**Comment by denpamusic** [comment]
Here's function you can use to restore missing values:
```php
/**
 * Restores values for non-unique keys in json object
 *
 * @param \Denpa\Bitcoin\Responses\Response
 *
 * @return array
 */
function restoreValues($response) : array
{
    $json = (string) $response->response()->getBody();

    // match object keys
    // (i. e. everything in quotes followed by
    // indefinite amount of spaces and semicolon)
    preg_match_all('/"([^"]+)"\s*:/', $json, $matches);

    // array of unique keys found in json string
    $keys = array_unique($matches[1]);

    $values = [];
    foreach($keys as $key) {
        // match values by key
        preg_match_all(sprintf('/"%s"\s*:\s*"([^"])"/', $key), $json, $matches);

        if (count($matches[1] ?? []) > 1) {
            // if there's more then one key with this name,
            // append all of it's values to the array
            $values[$key] = $matches[1];
        }
    }

    return array_merge($response->result(), $values);
}
```

For your example, it'll produce this output:
```php
$result = restoreValues(bitcoind()->request('masternode', 'outputs'));

/*
array(2) {
  ["1fff541fd048b032aca39cd4ed1a864b05cfa3b596bd02a471d807eb7cee4981"]=>
  array(3) {
    [0] =>
    string(1) "1"
    [1] =>
    string(1) "2"
    [2] =>
    string(1) "3"
  }
  ["11c07462fd35e438b6587c255e765912c8482c8fdc37191b102a1a2758eb4177"]=>
  string(1) "1"
}
*/
var_dump($result);
```

> ⚠️ Please note that using regex when dealing with json is unreliable and this function was created with single use case in mind and won't handle nested objects and such, so use with caution!

**Comment by bynicolas** [comment]
Hey, thanks for the quick reply.

Your function is almost perfect. The only adjustment I had to make was in the regex for `preg_match_all(sprintf('/"%s"\s*:\s*"([^"])"/', $key), $json, $matches);` 

I noticed that I was still missing some outputs, and found the issue with the regex.  

The fix is this one `preg_match_all(sprintf('/"%s"\s*:\s*"([^"]\d{0,3})"/', $key), $json, $matches);`. Notice how the capture groups looks for a any number between 0 and 999 `([^"]\d{0,3})`.  Your implementation was only giving back the outputs if the index was between 0 and 9.

So the function now looks like

```
    /**
     * Restores values for non-unique keys in json object
     *
     * @param \Denpa\Bitcoin\Responses\Response
     *
     * @return array
     */
    function restoreValues($response) : array
    {
        $matches = [];
        $json = (string) $response->response()->getBody();

        // match object keys
        // (i. e. everything in quotes followed by
        // indefinite amount of spaces and semicolon)
        preg_match_all('/"([^"]+)"\s*:/', $json, $matches);

        $values = [];
        foreach (array_unique($matches[1]) as $key) {
            // match values by key
            preg_match_all(sprintf('/"%s"\s*:\s*"([^"]\d{0,3})"/', $key), $json, $matches);

            if (count($matches[1] ?? []) > 1) {
                // if there's more then one key with this name,
                // append all of it's values to the array
                $values[$key] = $matches[1];
            }
        }

        return array_merge($response->get(), $values);
    }
```

And that works perfectly.

Thanks a bunch for your help.

I understand this is just a work around, but I wouldn't imagine Dash modifying their response any time soon... as this scenario is pretty much unlikely to occur on the Dash network , as it would imply someone creating, **in a single transaction**, multiple masternode outputs, requiring multiple thousand of DASH coins... --> $$$ !

This issues is likely to happen more often with lower caps coins, as it's the case here!

Any how, I digress..   Thanks again, this has been very helpful

**Comment by denpamusic** [comment]
Thanks for the update! Sorry I've actually missed '+' in that regex: `/"%s"\s*:\s*"([^"])"/`, should've been `/"%s"\s*:\s*"([^"]+)"/` but your implementation also works fine.

You might want to simplify your regex a bit by removing `[^"]` though, so it becomes: `preg_match_all(sprintf('/"%s"\s*:\s*"(\d{1,3})"/', $key), $json, $matches);`.

`[^"]` basically means - "match any single character, that is not "(double quotes)". This is redundant in you case, because you're already specifying that you're only want one to three digits with `\d{1,3}`.

Anyway glad I could help you and thanks for the heads up!

**Comment by bynicolas** [comment]
You are right, either `([^"]+)` or `(\d{1,3})` should be enough... both makes it redundant... 

Fixed it, Thanks
