### ISSUE TITLE
How to define two separate instance of different ports

### ISSUE THREAD

**Issue by M-Shahbaz** [denpamusic/laravel-bitcoinrpc#4]
This project is great and easy to work with bitcoin json rpc. 
As I was testing, is it possible to define other instance with different config settings, e.g: for a forked alt-coin which usually have same functionalities.

**Comment by denpamusic** [comment]
Sorry, this project was initially been designed to be used with single daemon, so as of now it's only possible to create separate instances manualy through use of underlying denpamusic/php-bitcoinrpc package.
``` php
use Denpa\Bitcoin\Client as LitecoinClient

$litecoin = new LitecoinClient(['port' => 9332, 'user' => '...', 'pass' => '...']);
$block = $litecoin->getBlock('a6b4e9d54a30c2aa8a9af64eb68f21b07166d96c69fe61f1c12b3896fd653b7b');
```
I'll mark it as a Feature Request though for the upcoming 2.0.x.

**Comment by denpamusic** [comment]
Turns out it's really easy to implement this, so it'll probably be available in v1.2.0 as early as Friday evening UTC after I've thoroughly test it.
For now I've created separate branch for this feature https://github.com/denpamusic/laravel-bitcoinrpc/tree/multi-instance

Basically you can now define separate configuration in `config/bitcoind.php` file, like [this one](https://github.com/denpamusic/laravel-bitcoinrpc/blob/multi-instance/config/config.php#L85) for litecoin.
Then you can select which configuration to use by simply passing it's name.
e. g.
```php
$block = bitcoind('litecoin')->getBlock('a6b4e9d54a30c2aa8a9af64eb68f21b07166d96c69fe61f1c12b3896fd653b7b');
```
Complete examples are available in updated [readme](https://github.com/denpamusic/laravel-bitcoinrpc/tree/multi-instance#multiple-instances).

Hope you'll find it useful!

**Comment by M-Shahbaz** [comment]
Ok, that is great.
Also as 0.17.0 is going to be released soon, it would be great to have ["Dynamic wallet load / create etc." ](https://github.com/bitcoin/bitcoin/issues/13059) feature integrated as well in future release of this project.

**Comment by denpamusic** [comment]
There's no need to change anything in project to support new RPC commands.
You can use it as soon as they are available in Core you can use it e. g. `bitcoind()->loadwallet('...'), bitcoind()->createwallet('...') etc.` or do you mean some other type of integration?

**Comment by denpamusic** [comment]
Thank you for your feature request!
Multiple instances are now implemented in [v1.2.0](https://github.com/denpamusic/laravel-bitcoinrpc/releases/tag/v1.2.0).
See release notes and [README](https://github.com/denpamusic/laravel-bitcoinrpc).

**Comment by M-Shahbaz** [comment]
> There's no need to change anything in project to support new RPC commands.
> You can use it, as soon as they are available in Core e. g. bitcoind()->loadwallet('...'), 
>  bitcoind()->createwallet('...') etc. or do you mean some other type of integration?
> 
[Multi-wallet](https://en.bitcoin.it/wiki/API_reference_(JSON-RPC)#Multi-wallet_RPC_calls) introduced in **0.15** and is done by setting the HTTP endpoint in the JSON-RPC request in the format <RPC IP address>:<RPC port>/wallet/<wallet name>, for example `https://127.0.0.1:8332/wallet/wallet1.dat`

All the other functions would be same, haven't checked how createwallet, loadwallet etc. will work in 0.17.0 release.

**Comment by denpamusic** [comment]
I see, sorry, wasn't aware of that.
It should be implemented in php-bitcoinrpc package then, not here.
It'll probably be called with something like `bitcoind()->wallet('wallet1.dat')->importaddress('...');`

**Comment by denpamusic** [comment]
[php-bitcoinrpc v2.0.6](https://github.com/denpamusic/php-bitcoinrpc/releases/tag/v2.0.6) now supports multi-wallet RPC.
As laravel-bitcoinrpc is a wrapper for that package you can now use it here too:
`$balance = bitcoind()->wallet('wallet1.dat')->getbalance();`

**Comment by M-Shahbaz** [comment]
That is great!
