### ISSUE TITLE
JSON value is not a string as expected

### ISSUE THREAD

**Issue by D3USHARP** [denpamusic/laravel-bitcoinrpc#8]
Code: 
```PHP
public function index() {

	$blockHash = '31e0cee91eb6a718b856dd451b2ef5592d03a087b1eb878564f13c6f9055697f';
	$blockInfo = bitcoind()->getblock($blockHash);
	return response()->json($blockInfo->get());

}
```

Error: 

> Denpa\Bitcoin\Exceptions\BitcoindException thrown with message "JSON value is not a string as expected"
Stacktrace:
#54 Denpa\Bitcoin\Exceptions\BitcoindException in C:\OSPanel\domains\btc.loc\vendor\denpa\php-bitcoinrpc\src\Client.php:151
#53 Denpa\Bitcoin\Client:request in C:\OSPanel\domains\btc.loc\vendor\denpa\php-bitcoinrpc\src\Client.php:213
#52 Denpa\Bitcoin\Client:__call in C:\OSPanel\domains\btc.loc\vendor\denpa\laravel-bitcoinrpc\src\ClientFactory.php:125
#51 Denpa\Bitcoin\ClientFactory:__call in C:\OSPanel\domains\btc.loc\app\Http\Controllers\BitcoinController.php:12
#50 App\Http\Controllers\BitcoinController:index in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54
#49 call_user_func_array in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54
#48 Illuminate\Routing\Controller:callAction in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php:45
#47 Illuminate\Routing\ControllerDispatcher:dispatch in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Route.php:212
#46 Illuminate\Routing\Route:runController in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Route.php:169
#45 Illuminate\Routing\Route:run in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Router.php:679
#44 Illuminate\Routing\Router:Illuminate\Routing\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:30
#43 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php:41
#42 Illuminate\Routing\Middleware\SubstituteBindings:handle in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#41 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#40 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php:75
#39 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#38 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#37 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php:49
#36 Illuminate\View\Middleware\ShareErrorsFromSession:handle in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#35 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#34 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php:63
#33 Illuminate\Session\Middleware\StartSession:handle in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#32 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#31 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php:37
#30 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#29 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#28 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php:66
#27 Illuminate\Cookie\Middleware\EncryptCookies:handle in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#26 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#25 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:104
#24 Illuminate\Pipeline\Pipeline:then in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Router.php:681
#23 Illuminate\Routing\Router:runRouteWithinStack in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Router.php:656
#22 Illuminate\Routing\Router:runRoute in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Router.php:622
#21 Illuminate\Routing\Router:dispatchToRoute in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Router.php:611
#20 Illuminate\Routing\Router:dispatch in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:176
#19 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:30
#18 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\OSPanel\domains\btc.loc\vendor\fideloper\proxy\src\TrustProxies.php:57
#17 Fideloper\Proxy\TrustProxies:handle in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:31
#14 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:31
#11 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php:27
#8 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php:62
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:104
#2 Illuminate\Pipeline\Pipeline:then in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in C:\OSPanel\domains\btc.loc\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in C:\OSPanel\domains\btc.loc\public\index.php:55

Bitcoin.conf: 
> rpcuser=userrpc
rpcpassword=rpcpassw
rpcport=18443
regtest=1
server=1

<details>
  <summary>Spoiler</summary>
  bitcoind()->getbestblockhash();
  

> getbestblockhash Returns the hash of the best (tip) block in the longest blockchain. Result: "hex" (string) the block hash hex encoded Examples: > bitcoin-cli getbestblockhash > curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getbestblockhash", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/

</details>

**Comment by denpamusic** [comment]
Hi!
Thank you for detailed issue!
This should now be fixed in version 2.0.8 of php-bitcoinrpc and 1.2.4 of this package.
Please update and confirm that everything works.
Thanks.

**Comment by D3USHARP** [comment]
Everything works, thank you.

**Comment by feishaos** [comment]
[-1] BadRemoteCallException in Handler.php line 74
JSON value is not a string as expected
     * @return \Throwable|null
     */
    protected function requestExceptionHandler(Throwable $exception) : ?Throwable
    {
        if ($exception instanceof RequestException) {
            if (
                $exception->hasResponse() &&
                $exception->getResponse()->hasError()
            ) {
                return new BadRemoteCallException($exception->getResponse());
            }

            return new ConnectionException(
                $exception->getRequest(),
                $exception->getMessage(),
                $exception->getCode()
            );
        }


composer show:
denpa/php-bitcoinrpc          v2.1.0             Bitcoin JSON-RPC client based on GuzzleHttp


what's the problem?
